baseURL = 'https://bujo-blog.netlify.app/'
locale = 'en-us'
title = 'The Bullet Journal Guide'
theme = 'PaperMod'

[params]
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
